
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.190.128:3306/gulimall_oms
    username: root
    password: 123456
#    rabbitmq的配置
  rabbitmq:
    host: 192.168.190.128
    port: 5672
    virtual-host: /
    username: admin
    password: 123456
    # 消息抵达交换机的后调
    publisher-confirm-type: correlated
    #消息由交换机抵达队列的回调
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual  #前两种ack不自动ack
      direct:
        acknowledge-mode: manual  #后三种ack不自动ack

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 9000
